// Code generated by gen_proto.sh.
// DO NOT EDIT!

class MessageData{
    public Map:{[key:number] : any} = {};
    public IDToStringMap:{[key:number] : string} = {};
    public BackendLogin :number = 1;
	public UpGetBackendLoginInfo :number = 2;
	public DownGetBackendLoginInfo :number = 3;
	public TestToAgent :number = 4;
	public TestToGame :number = 5;
	public UpPing :number = 6;
	public DownPing :number = 7;
	public WebUpRegister :number = 8;
	public WebDownRegister :number = 9;
	public WebUpGetServerInfo :number = 10;
	public WebDownGetServerInfo :number = 11;
	public ServerInfo :number = 12;
	public UpGetConfigToCenter :number = 13;
	public SyncConfigDataToAll :number = 14;
	public LoginKickPlayerToAgent :number = 15;
	public AgentCheckUserToLogin :number = 16;
	public LoginCheckPlayerToAgent :number = 17;
	public PlayerLogin :number = 18;
	public PlayerLoginToGame :number = 19;
	public DownPlayerLogin :number = 20;
	public WebUpRegisterPassword :number = 21;
	public WebDownRegisterPassword :number = 22;
	public Frame :number = 23;
	public Login :number = 24;
	public TestStruct :number = 25;
	
    public init(){
        this.Map[this.BackendLogin] = pb.BackendLogin;
	    this.Map[this.UpGetBackendLoginInfo] = pb.UpGetBackendLoginInfo;
	    this.Map[this.DownGetBackendLoginInfo] = pb.DownGetBackendLoginInfo;
	    this.Map[this.TestToAgent] = pb.TestToAgent;
	    this.Map[this.TestToGame] = pb.TestToGame;
	    this.Map[this.UpPing] = pb.UpPing;
	    this.Map[this.DownPing] = pb.DownPing;
	    this.Map[this.WebUpRegister] = pb.WebUpRegister;
	    this.Map[this.WebDownRegister] = pb.WebDownRegister;
	    this.Map[this.WebUpGetServerInfo] = pb.WebUpGetServerInfo;
	    this.Map[this.WebDownGetServerInfo] = pb.WebDownGetServerInfo;
	    this.Map[this.ServerInfo] = pb.ServerInfo;
	    this.Map[this.UpGetConfigToCenter] = pb.UpGetConfigToCenter;
	    this.Map[this.SyncConfigDataToAll] = pb.SyncConfigDataToAll;
	    this.Map[this.LoginKickPlayerToAgent] = pb.LoginKickPlayerToAgent;
	    this.Map[this.AgentCheckUserToLogin] = pb.AgentCheckUserToLogin;
	    this.Map[this.LoginCheckPlayerToAgent] = pb.LoginCheckPlayerToAgent;
	    this.Map[this.PlayerLogin] = pb.PlayerLogin;
	    this.Map[this.PlayerLoginToGame] = pb.PlayerLoginToGame;
	    this.Map[this.DownPlayerLogin] = pb.DownPlayerLogin;
	    this.Map[this.WebUpRegisterPassword] = pb.WebUpRegisterPassword;
	    this.Map[this.WebDownRegisterPassword] = pb.WebDownRegisterPassword;
	    this.Map[this.Frame] = pb.Frame;
	    this.Map[this.Login] = pb.Login;
	    this.Map[this.TestStruct] = pb.TestStruct;
	    

        this.IDToStringMap[this.BackendLogin] = "BackendLogin";
	    this.IDToStringMap[this.UpGetBackendLoginInfo] = "UpGetBackendLoginInfo";
	    this.IDToStringMap[this.DownGetBackendLoginInfo] = "DownGetBackendLoginInfo";
	    this.IDToStringMap[this.TestToAgent] = "TestToAgent";
	    this.IDToStringMap[this.TestToGame] = "TestToGame";
	    this.IDToStringMap[this.UpPing] = "UpPing";
	    this.IDToStringMap[this.DownPing] = "DownPing";
	    this.IDToStringMap[this.WebUpRegister] = "WebUpRegister";
	    this.IDToStringMap[this.WebDownRegister] = "WebDownRegister";
	    this.IDToStringMap[this.WebUpGetServerInfo] = "WebUpGetServerInfo";
	    this.IDToStringMap[this.WebDownGetServerInfo] = "WebDownGetServerInfo";
	    this.IDToStringMap[this.ServerInfo] = "ServerInfo";
	    this.IDToStringMap[this.UpGetConfigToCenter] = "UpGetConfigToCenter";
	    this.IDToStringMap[this.SyncConfigDataToAll] = "SyncConfigDataToAll";
	    this.IDToStringMap[this.LoginKickPlayerToAgent] = "LoginKickPlayerToAgent";
	    this.IDToStringMap[this.AgentCheckUserToLogin] = "AgentCheckUserToLogin";
	    this.IDToStringMap[this.LoginCheckPlayerToAgent] = "LoginCheckPlayerToAgent";
	    this.IDToStringMap[this.PlayerLogin] = "PlayerLogin";
	    this.IDToStringMap[this.PlayerLoginToGame] = "PlayerLoginToGame";
	    this.IDToStringMap[this.DownPlayerLogin] = "DownPlayerLogin";
	    this.IDToStringMap[this.WebUpRegisterPassword] = "WebUpRegisterPassword";
	    this.IDToStringMap[this.WebDownRegisterPassword] = "WebDownRegisterPassword";
	    this.IDToStringMap[this.Frame] = "Frame";
	    this.IDToStringMap[this.Login] = "Login";
	    this.IDToStringMap[this.TestStruct] = "TestStruct";
	    
    }
}
