package pb

// Code generated by gen_proto.sh.
// DO NOT EDIT!

import (
	"github.com/chaos007/easycome/libs/msgmeta"
)

func init() {
	msgmeta.RegisterMessageMeta("pb.BackendLogin", 1)
	msgmeta.RegisterMessageMeta("pb.UpGetBackendLoginInfo", 2)
	msgmeta.RegisterMessageMeta("pb.DownGetBackendLoginInfo", 3)
	msgmeta.RegisterMessageMeta("pb.TestToAgent", 4)
	msgmeta.RegisterMessageMeta("pb.TestToGame", 5)
	msgmeta.RegisterMessageMeta("pb.UpPing", 6)
	msgmeta.RegisterMessageMeta("pb.DownPing", 7)
	msgmeta.RegisterMessageMeta("pb.WebUpRegister", 8)
	msgmeta.RegisterMessageMeta("pb.WebDownRegister", 9)
	msgmeta.RegisterMessageMeta("pb.WebUpGetServerInfo", 10)
	msgmeta.RegisterMessageMeta("pb.WebDownGetServerInfo", 11)
	msgmeta.RegisterMessageMeta("pb.ServerInfo", 12)
	msgmeta.RegisterMessageMeta("pb.UpGetConfigToCenter", 13)
	msgmeta.RegisterMessageMeta("pb.SyncConfigDataToAll", 14)
	msgmeta.RegisterMessageMeta("pb.LoginKickPlayerToAgent", 15)
	msgmeta.RegisterMessageMeta("pb.AgentCheckUserToLogin", 16)
	msgmeta.RegisterMessageMeta("pb.LoginCheckPlayerToAgent", 17)
	msgmeta.RegisterMessageMeta("pb.PlayerLogin", 18)
	msgmeta.RegisterMessageMeta("pb.PlayerLoginToGame", 19)
	msgmeta.RegisterMessageMeta("pb.DownPlayerLogin", 20)
	msgmeta.RegisterMessageMeta("pb.WebUpRegisterPassword", 21)
	msgmeta.RegisterMessageMeta("pb.WebDownRegisterPassword", 22)
	msgmeta.RegisterMessageMeta("pb.Frame", 23)
	msgmeta.RegisterMessageMeta("pb.TestStruct", 24)

}
